### PR TITLE
Fix spelling typo

### PR DESCRIPTION
**Pull request by ronaldbradford**
- [Y] I confirm that all the content in this pull request is original work and I am the original author
- [Y] I have nothing that prevents me from submitting this work (like a clause in a work contract)
- [Y] I understand that the work I am submitting will be released under the terms of the licence of this repository
- [Y] I have double-checked all of the above and checked the tick-boxes

PS. licence  in your template should be updated to "license"

### CODE REVIEW

**Comment by Robbbb** [comment]
Thanks!
I'm a poor speller.

**Comment by ronaldbradford** [comment]
FYI, the results of your tool enabled me to create https://photos.app.goo.gl/1vo8V3UHAziZgj2E8.

One suggestion, allow for defining the size for the font for numbers, I had to mess with that on the graphic to make metric readable.

**Comment by darigovresearch** [comment]
@ronaldbradford thanks for the suggestion & nice work on the rulers

**Comment by darigovresearch** [comment]
Issue has been raised https://github.com/Robbbb/VectorRuler/issues/39, did you want to put in another pull request for this feature @ronaldbradford ?

**Pull request merged**
