### PR TITLE
Improve rule generation adding left hand ruler, negative numbers, from-to capabilities

### LINKED ISSUE #37: [FEATURE REQUEST] Left Hand Ruler
Being able to create a left hand ruler would be useful

### LINKED ISSUE #40: [FEATURE REQUEST] Rotate Text
I'm making vertical rulers and would like an option to rotate the letters + or - 90 or 180 degrees. Otherwise, this code is awesome!

### PR DESCRIPTION
**Pull request by riverwind0**
Update code to allow negative values, left hand ruler and minor adjustments

- [X] I confirm that all the content in this pull request is original work and I am the original author
- [X] I have nothing that prevents me from submitting this work (like a clause in a work contract)
- [X] I understand that the work I am submitting will be released under the terms of the licence of this repository
  - [X] I have double-checked all of the above and checked the tick-boxes

### CODE REVIEW

**Comment by Robbbb** [comment]
Wow, thank you so much!

**Comment by Robbbb** [comment]
Heya @riverwind0 !
Super grateful for these great features!
I know almost nothing about javascrtipt and this tool was authored by me a long time ago with lots of help from a friend. 
I merged this, and then tested it by swapping the target of the github pages branch from the "gh-pages" brand to "master"
Sadly, the preview didn't work, and neither did the export. 
I have switched the pages target back to "master"
Do you have any ideas?

**Comment by riverwind0** [comment]
Mmm. Strange. I tested in local and it worked fine (also the exporting process). I will check it and I will ping you.

**Comment by riverwind0** [comment]
I tried the code starting a local web server and it works fine. Can you tell me exactly what is the environment for your real web server? I will try to reproduce the same env to check if something is failing...
The changes I did don't touch any config relevant for the server deployment itself.
image

image

**Comment by Robbbb** [comment]
Heya! I don't have anything local set up. I just merged it and then tried to adjust the github pages source repo and then it failed. 
I went ahead and added you as a collaborator on the project, want to give merging it a shot? 
I think I did it wrong, now the "master" (I would love to rename this main) repo is well ahead of the gh-pages repo. 
I don't know how any of this works

**Comment by riverwind0** [comment]
Ok. Don't worry. I will check it tomorrow and I will ping you when I check what's the problem. ;)

**Comment by riverwind0** [comment]
Ok. I had time to check the deployment. If I deploy the modified code from my gitHub repo, it worked fine.
You can test it using this URL: [https://riverwind0.github.io/VectorRuler/
](https://riverwind0.github.io/VectorRuler/
)
In theory, I followed the same building and deployment process you've in your repo. Maybe could be something related with the cache of your browser? Can you try to re-deploy it and browse using an incognito browser?

image
image

**Comment by Robbbb** [comment]
I really appreciate you testing it! 
It looks great! Being able to do reverse rulers and negative numbers is pretty cool!
I think you can merge it yourself, I have granted you collaborator on the repo. 
I don't know how to do it, but I can learn if it is needed!

Also, a thought:
I find it a little confusing that it has start, end, and width. 
I think we can get rid of width completely and just have start and end. 
How does that sound?

**Comment by riverwind0** [comment]
Totally agree. I will update the code to adjust automatically the width based on the start and end numbers. ;)

**Pull request merged**
