### PR TITLE
Add a text box to let user insert pixel per inch

### PR DESCRIPTION
**Pull request by pci06**
Hello,
On computer with 96 DPI, the 72 DPI default gives wrong millimeter width.
pci.

### CODE REVIEW

**Comment by Robbbb** [comment]
Hi Pci!

Thanks for the work you put into this!
Is it live somewhere for me to test out before merging?
I think that this has the potential to be very helpful, but also it has the potential to confuse users.
Can you tell me the steps to reproduce the bug? Was the SVG the wrong scale on your screen? When printed? In vector software?

Ideally we would use the actual units we are building a ruler with, mm for mm, inches for inches.
[SVG has support for units](https://mpetroff.net/2013/08/analysis-of-svg-units/), but I am not sure Paper.JS does.

looking forward to hearing more!

**Comment by Robbbb** [comment]
Hey @pci06 ! 
I am open to merging this, but still confused about what software the DPI issue was causing issues in.

**Comment by darigovresearch** [comment]
@pci06 thanks for the pull request, are you able to generate a GitHub page of your fork so the feature can be tested?

Could you please also advise to help clarify the confusion with @Robbbb ?

**Comment by Robbbb** [comment]
Also note this pull would revert the SVG export code to the broken version, preventing export.

**Comment by Robbbb** [comment]
I merged it with copy and paste because I don't know how to use github. Thanks @pci06 !!!

**Pull request closed without merging**
